Feat/#10 search box
Team-SoFa/SoFa-server pull request #21
Opened 2024-11-29 19:01 UTC by minibr

## 📌 작업 내용
- Ai_Tag/Custom_Tag Api 작업
- LinkCard 검색창 구현
- Tag 검색 기능 추가

## 📝 변경 사항
- Tag, Custom_Tag 별도의 테이블에서 관리
- Custom_Tag CRUD 
- Ai_Tag/Custom_Tag Api 
- Tag 검색 
- Linkcard 검색 (태그별/폴더별/태그+폴더/전체)
- 검색 정렬 조회

## ✅ Github 이슈
- #10 

## 💡 ETC

>

2024-12-01 12:56 UTC, ckdals4600 requested changes

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/auth/config/GoogleOAuth2Config.java
혹시 해당 파일과 OAuth2Controller 삭제하신 이유가 있으실까요?

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/searchbox/api/SearchBoxApi.java
폴더 검색, 태그 검색, 폴더 태그 검색 API를 분리하지 않고 구현은 불가능한걸까요?
이렇게 나누면 프론트팀에서 api호출할때 불편함이 많을거 같습니다!

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/searchbox/dto/request/SearchBoxReq.java
해당 클래스 사용부분이 없는거 같습니다! 삭제 부탁드립니다

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/searchbox/repository/SearchBoxCustomRepositoryImpl.java
> +    }
API에 남긴 리뷰와 같이 위 함수에 where 절에 사용되는 함수들을 보면 null 처리가 되어 있어 그냥 해당 함수로 통일해도 될거 같습니다!

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/searchbox/service/SearchBoxService.java
> +        Long lastIdLong = "0".equals(lastId) ? 0L : EncryptionUtil.decrypt(lastId);
암호화된 id 가 0인 경우 아예 오류여서 해당 부분은 오류처리로 해주셔야 같습니다!

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/searchbox/service/SearchHistoryService.java
> +    @SuppressWarnings("unchecked")
해당 어노테이션 역할은 무엇일까요 ?

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/api/TagApi.java
혹시 태그 관련 커밋도 다 search box 브랜치에 있는걸까요 ?

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/controller/TagController.java
> +                .toList());
Entity의 경우 controller level 까지 보여지면 안된다고 생각합니다.
Entity가 Dto로 변경하는 과정은 서비스단에서 처리되어야 하며, 서비스에서 컨트롤러에 전달하는 데이터는 DTO 형식으로 부탁드립니다!
추가로 ResponseEntity.ok 말고 BaseResponse.ok() 로 변경가능할까요?
아래 코드들도 동일하게 수정해주시면 감사하겠습니다

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/controller/TagController.java
> +    public ResponseEntity<List<CustomTagRes>> getAllCustomTags(@RequestParam Member member) {
List의 경우 바로 전달하지 말고 Dto로 다시 감싼 후 전달 가능할까요 ?
아래는 예시 코드입니다!
```
public record customTagListRes(List<CustomTagRes> customTagList) {
}

```

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/entity/CustomTag.java
> -    public String getEncryptUserId() {
이름 변경해주셔서 감사합니다!

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/entity/Tag.java
> +        indexes = {
해당 어노테이션과 옵션을 처음 봤는데 어떤 용도인지 궁금합니다!

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/security/config/SecurityConfig.java
> +                                .requestMatchers(PERMIT_URLS).permitAll()
변경 감사합니다 ㅎㅎ

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/security/jwt/provider/JwtTokenProvider.java
> +
제가 해당 기능을 StringUtils 에 간단하게 구현했었는데 혹시 해당 기능이 JwtTokenProvider로 이동 된 이유가 있을까요 ?

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/security/jwt/filter/JwtAuthenticationFilter.java
> +        if (token != null && jwtTokenProvider.validateToken(token)) {
이 부분도 RequestUtils에서 변경하신 이유가 궁금합니다!

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/member/controller/MemberController.java
> -@RequestMapping("/api/member")
수정 감사합니다 👍

2024-12-01 12:56 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/folder/service/FolderService.java
> +                .member(member)  //추가함 멤버 받아야해서
제가 놓친 부분인데 확인해주셔서 감사합니다!

2024-12-01 15:38 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/security/config/SecurityConfig.java
> +            "/login/oauth2/code/*",
해당 부분에서 url 매핑이 `"/login/oauth2/code/**"` 식으로 되어야 하는데 오타가 난 거 같습니다!
혹시 제가 모르는 문법이라면 설명부탁드려요 😄

2024-12-02 09:29 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/security/config/SecurityConfig.java
> +            "/login/oauth2/code/**",
OAuth2Controller 보면 엔드포인트 Prefix가 `login/` 인거 같은데 그럼 해당 부분이 'login/**'으로 변경되어야 하는거 같습니다!

2024-12-02 10:32 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/controller/CustomTagController.java
> +    }
Entity는 서비스에서 DTO로 변환 후 controller에 반환 부탁드립니다!
추가로 컨트롤러는 service 외에 의존성을 갖지 않게 ```EncryptionUtil.decrypt(id)```와 같은 로직들 전부 서비스 단으로 이동 부탁드립니다!
또한 암호화 로직은 Entity 내부의 getEncryptionId() 메소드로 수정해주세요

2024-12-02 10:32 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/controller/TagController.java
> +    }
해당 부분도 수정 부탁드립니다!

2024-12-02 10:32 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/dto/response/TagSearchRes.java
> +    private Long id;
Id 값은 암호화 부탁드립니다!

2024-12-02 10:32 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/api/CustomTagApi.java
CustomTag와 Tag의 경우 추천 시스템과 AI 작업으로 인해 나눈 개념이라고 생각되며, 사용자 측면에서는 해당 부분들이 하나의 Tag로 인식된다고 생각됩니다!
추가, 삭제, 수정 같은 부분은 상관없지만 조회나 검색의 경우 Tag와 통합 가능하실까요?

2024-12-04 11:01 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/controller/CustomTagController.java
> +@RequestMapping("/custom-tags")
camel 규칙으로 수정해주세요!

2024-12-04 11:04 UTC, ckdals4600 commented on src/main/java/com/sw19/sofa/domain/tag/api/CustomTagApi.java
> +    ResponseEntity<List<CustomTagRes>> getAllCustomTags(@AuthMember Member member);
커스텀 태그만 조회하는 경우는 필요없다고 생각됩니다! 
AI 태그와 커스텀 태그 한번에 조회하는 로직이 필요할거 같습니다!

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/searchbox/api/SearchBoxApi.java
API 엔드포인트가 너무 분리되어 있어 프론트엔드에서 API를 호출할 때 분기 처리가 많아질 수 있을거같다 말씀이신가요? 제 의견으로는 현재 구조가 각 검색 유형별로 명확히 구분되어 있어 명시적이고 이해하기 쉬울거같기도하고
하나의 엔드포인트로 합치면 복잡한 파라미터 처리와 분기 로직이 백엔드로 이동 될거같아서 이렇게 구현했었습니다. 

변경예정

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/searchbox/service/SearchHistoryService.java
> +    @SuppressWarnings("unchecked")
타입 캐스팅이 안전하지 않을 수 있다는 경고 무시하도록 하는 어노테이션입니다. 만약 없으면 코드는 정상 동작은하지만 노란색 경고줄이 표시됨

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/security/jwt/filter/JwtAuthenticationFilter.java
> +        if (token != null && jwtTokenProvider.validateToken(token)) {
원래는 RequestUtils를 통해 Access Token 존재 여부만 확인인데 JwtTokenProvider를 통해 토큰을 추출하고 바로 검증하여 토큰 추출과 검증을 한번에 처리하여 코드가 더 깔끔해져 변경한거 같습나다.

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/security/jwt/provider/JwtTokenProvider.java
> +
JwtTokenProvide에서 JWT 토큰과 관련된 모든 작업 담당을 한다고 생각해 토큰 추출, 검증, 생성 같은 JWT 관련 로직을 한 곳에서 관리하는것이라 생각했습니다

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/auth/config/GoogleOAuth2Config.java
이름이 변경되어 삭제되었습니다.

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/searchbox/repository/SearchBoxCustomRepositoryImpl.java
> +    }
해결했습니다.

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/security/config/SecurityConfig.java
> +            "/login/oauth2/code/**",
변경 하였습니다.

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/tag/dto/response/TagSearchRes.java
> +    private Long id;
Encryption했습니다.

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/tag/dto/request/CustomTagReq.java
id 필드 추가 하여 암호화된 ID를 받게 해주었습니다.

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/tag/controller/TagController.java
> +    }
Entity는 서비스에서 DTO로 변환 ✅
service 외에 의존성을 갖지 않게 ✅ 
암호화 로직은 Entity 내부의 getEncryptedId() 메소드로 ✅

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/tag/controller/CustomTagController.java
> +    }
Entity는 서비스에서 DTO로 변환 ✅
service 외에 의존성을 갖지 않게 ✅ 
암호화 로직은 Entity 내부의 getEncryptedId() 메소드로 ✅

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/tag/api/CustomTagApi.java
두 타입의 tag를 검색하는 일은 없으니 각각의 검색api을 삭제하여 수정하였습니다.

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/tag/api/CustomTagApi.java
> +    ResponseEntity<List<CustomTagRes>> getAllCustomTags(@AuthMember Member member);
네 맞습니다. 태그+커스텀태그 가 모든 태그 검색만 있으면 됩니다.
수정하였습니다.

2024-12-04 17:04 UTC, minibr commented on src/main/java/com/sw19/sofa/domain/tag/controller/CustomTagController.java
> +@RequestMapping("/custom-tags")
네 수정했습니다.

2024-12-05 19:34 UTC, ckdals4600 approved these changes

2024-12-05 19:35 UTC, merged